name: Deploy to Hetzner

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f Clocktower.Server/Dockerfile -t clocktower-server .

      - name: Save Docker image to tar
        run: docker save clocktower-server -o clocktower-server.tar

      - name: Create .env file
        run: |
          cat > .env << EOF
          ASPNETCORE_ENVIRONMENT=Production
          Secrets__DiscordBotToken=${{ secrets.DISCORD_BOT_TOKEN }}
          Secrets__DiscordClientId=${{ secrets.DISCORD_CLIENT_ID }}
          Secrets__DiscordClientSecret=${{ secrets.DISCORD_CLIENT_SECRET }}
          Secrets__DiscordRedirectUri=${{ vars.DISCORD_REDIRECT_URI }}
          Secrets__DiscordBotRedirectUri=${{ vars.DISCORD_BOT_REDIRECT_URI }}
          Secrets__FeUri=${{ vars.FE_URI }}
          APP_UID=1000
          EOF

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "clocktower-server.tar,.env"
          target: "/root"
          options: "-o StrictHostKeyChecking=no"

      - name: Load and run container on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /root/clocktower-server.tar
            docker stop clocktower-server || true
            docker rm clocktower-server || true
            docker run -d --name clocktower-server -p 80:8080 --env-file /root/.env clocktower-server
          options: "-o StrictHostKeyChecking=no"

